"""initial schema

Revision ID: e82be52836d2
Revises: 
Create Date: 2026-09-03 18:24:03.439196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e82be52836d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Must come first: the companies index below uses gin_trgm_ops, which does
    # not exist until the extension is installed. Autogenerate produced the
    # index but not the extension, so a migration against a fresh database
    # failed on the very table it was creating.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('naics', sa.String(length=8), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('employee_count_is_estimate', sa.Boolean(), nullable=False),
    sa.Column('revenue_usd', sa.Float(), nullable=True),
    sa.Column('revenue_is_estimate', sa.Boolean(), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('peer_count_in_niche', sa.Integer(), nullable=True),
    sa.Column('web', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.Column('quality_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('data_quality IS NULL OR (data_quality >= 0 AND data_quality <= 100)', name='ck_companies_data_quality_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_city'), 'companies', ['city'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index('ix_companies_industry_city', 'companies', ['industry', 'city'], unique=False)
    op.create_index(op.f('ix_companies_naics'), 'companies', ['naics'], unique=False)
    op.create_index('ix_companies_name_trgm', 'companies', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_companies_state'), 'companies', ['state'], unique=False)
    op.create_table('http_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_http_cache_expires_at'), 'http_cache', ['expires_at'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_status', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('phone_valid', sa.Boolean(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('is_decision_maker', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_contacts_company_email')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_payloads_company_id'), 'raw_payloads', ['company_id'], unique=False)
    op.create_index(op.f('ix_raw_payloads_source'), 'raw_payloads', ['source'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('buy_box', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_scores_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index(op.f('ix_scores_company_id'), 'scores', ['company_id'], unique=False)
    op.create_index(op.f('ix_scores_engine_version'), 'scores', ['engine_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_engine_version'), table_name='scores')
    op.drop_index(op.f('ix_scores_company_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_raw_payloads_source'), table_name='raw_payloads')
    op.drop_index(op.f('ix_raw_payloads_company_id'), table_name='raw_payloads')
    op.drop_table('raw_payloads')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_http_cache_expires_at'), table_name='http_cache')
    op.drop_table('http_cache')
    op.drop_index(op.f('ix_companies_state'), table_name='companies')
    op.drop_index('ix_companies_name_trgm', table_name='companies', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_companies_naics'), table_name='companies')
    op.drop_index('ix_companies_industry_city', table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_city'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
